// app/components/landing/experience.tsx
import React from "react";
import FadeIn from "../animations/fadeIn";
import Heading from "../heading";
import { formatDate } from "@/lib/utils";
import { IndexPageType } from "@/lib/types/pages";

function Experience({
  experience,
}: {
  experience: IndexPageType["experience"];
}) {
  return (
    <FadeIn delay={0.6}>
      <div className="px-0 !pt-0 gap-8 sm:gap-6 lg:gap-8">
        <div className="mb-4">
          <Heading size="default">{experience.title}</Heading>
        </div>
        <ul className="list-disc list-inside text-sm sm:text-md lg:text-sm flex flex-col gap-2">
          {experience.items.map((item) => (
            <li
              key={item.position}
              className="w-full flex items-center gap-1 text-sm"
            >
              <div className="text-muted-foreground">
                {typeof item.date === "string"
                  ? item.date
                  : formatDate(item.date)}
              </div>
              <hr className="grow bg-bg-muted" />
              <a
                href={item.company.url}
                className="flex items-center gap-1 text-muted-foreground hover:text-foreground transition-colors"
                target="_blank"
                rel="noopener noreferrer"
              >
                <div className="font-sm">{item.position}</div>
                <span>at</span>
                <span className="font-medium">{item.company.name}</span>
              </a>
            </li>
          ))}
        </ul>
      </div>
    </FadeIn>
  );
}

export default Experience;

// app/components/landing/Experience.vue
<template>
  <section class="gap-8 sm:gap-6 lg:gap-8">
    <SharedHeading :title="page.experience.title" size="md" class="mb-4" />
    <ul class="w-full">
      <li
        v-for="job in page.experience.items"
        :key="job.position"
        class="w-full flex items-center gap-1 mb-2 text-sm text-muted"
      >
        <div>{{ job.date }}</div>
        <hr class="grow border-muted w-man" />
        <NuxtLink
          :to="job.company.url"
          class="hover:text-default shrink-0 flex gap-1 transition-colors duration-150"
        >
          <div>{{ job.position }}</div>
          <div>at</div>
          <div class="font-medium">
            {{ job.company.name }}
          </div>
        </NuxtLink>
      </li>
    </ul>
  </section>
</template>

<script lang="ts" setup>
interface Job {
  position: string;
  date: string;
  company: {
    name: string;
    url: string;
  };
}
defineProps<{
  page: {
    experience: {
      title: string;
      items: Job[];
    };
  };
}>();
</script>

<style></style>
