// components/landing/Hero.vue
<script setup lang="ts">
import type { IndexCollectionItem } from "@nuxt/content";

const { footer, global } = useAppConfig();

defineProps<{
  page: IndexCollectionItem;
}>();
</script>

<template>
  <div class="flex flex-col items-center justify-center h-[400px] gap-4">
    <div class="flex items-center justify-center">
      <Motion
        :initial="{
          scale: 1.1,
          opacity: 0,
          filter: 'blur(20px)',
        }"
        :animate="{
          scale: 1,
          opacity: 1,
          filter: 'blur(0px)',
        }"
        :transition="{
          duration: 0.6,
          delay: 0.1,
        }"
      >
        <img
          class="w-24 h-24 object-fill rounded-full border-2 border-muted"
          :src="global.picture.src"
        />
      </Motion>
    </div>

    <div class="max-w-lg mx-auto">
      <Motion
        :initial="{
          scale: 1.1,
          opacity: 0,
          filter: 'blur(20px)',
        }"
        :animate="{
          scale: 1,
          opacity: 1,
          filter: 'blur(0px)',
        }"
        :transition="{
          duration: 0.6,
          delay: 0.1,
        }"
      >
        <p
          class="text-shadow-md text-4xl font-bold text-center tracking-tight text-pretty"
        >
          {{ page.title }}
        </p>
      </Motion>
    </div>
    <div class="text-muted text-center mx-auto max-w-2xl text-balance">
      <Motion
        :initial="{
          scale: 1.1,
          opacity: 0,
          filter: 'blur(20px)',
        }"
        :animate="{
          scale: 1,
          opacity: 1,
          filter: 'blur(0px)',
        }"
        :transition="{
          duration: 0.6,
          delay: 0.3,
        }"
      >
        {{ page.description }}
      </Motion>
    </div>

    <div clas="mt-4 flex-col justify-center items-center">
      <Motion
        :initial="{
          scale: 1.1,
          opacity: 0,
          filter: 'blur(20px)',
        }"
        :animate="{
          scale: 1,
          opacity: 1,
          filter: 'blur(0px)',
        }"
        :transition="{
          duration: 0.6,
          delay: 0.5,
        }"
      >
        <div v-if="page.hero.links" class="flex items-center gap-2">
          <UButton v-bind="page.hero.links[0]" />
          <UButton
            :color="global.available ? 'success' : 'error'"
            variant="ghost"
            class="gap-2"
            :to="global.available ? global.meetingLink : ''"
            :label="
              global.available ? 'Available' : 'Not available at the moment'
            "
          >
            <template #leading>
              <span class="relative flex size-2">
                <span
                  class="absolute inline-flex size-full rounded-full opacity-75"
                  :class="
                    global.available ? 'bg-success animate-ping' : 'bg-error'
                  "
                />
                <span
                  class="relative inline-flex size-2 scale-90 rounded-full"
                  :class="global.available ? 'bg-success' : 'bg-error'"
                />
              </span>
            </template>
          </UButton>
        </div>
      </Motion>
    </div>
  </div>
</template>

// app/components/landing/hero.tsx
"use client";

import React from "react";
import Heading from "../heading";
import { Button } from "../button";
import Link from "next/link";

import FadeIn from "../animations/fadeIn";

type Props = {
  title: string;
  description: string;
  picture: {
    src: string;
    alt: string;
  };
  meetingLink: string;
  available: boolean;
  links?: { to?: string; label: string }[];
};

function Hero({
  title,
  description,
  picture,
  meetingLink,
  available,
  links,
}: Props) {
  return (
    <div className="w-full flex flex-col items-center justify-center gap-4">
      <FadeIn delay={0.1}>
        <img
          src={picture.src}
          alt={picture.alt}
          className="w-24 h-24 border-2 border-border rounded-full"
        />
      </FadeIn>
      <div className="max-w-xl mx-auto">
        <FadeIn delay={0.1}>
          <Heading size="big" className="text-center text-shadow-md">
            {title}
          </Heading>
        </FadeIn>
      </div>
      <FadeIn delay={0.3}>
        <p className="text-muted-foreground text-center mx-auto max-w-2xl text-balance">
          {description}
        </p>
      </FadeIn>
      <FadeIn delay={0.5}>
        <div className="flex gap-2">
          {links && links.length > 0 && links[0].to && (
            <Button asChild>
              <Link href={links[0].to} className="flex gap-2 items-center">
                {links[0].label}
              </Link>
            </Button>
          )}
          <Button
            variant="ghost"
            color={available ? "success" : "destructive"}
            asChild
          >
            <Link
              href={meetingLink}
              target="_blank"
              rel="noopener noreferrer"
              className="flex gap-2 items-center"
            >
              <span className="relative flex size-2">
                <span
                  className={`
                  absolute inline-flex size-full rounded-full opacity-75
                  ${available ? "bg-success animate-ping" : "bg-destructive"}
                  `}
                />
                <span
                  className={`
                  relative inline-flex size-2 scale-90 rounded-full
                  ${available ? "bg-success" : "bg-destructive"}
                  `}
                />
              </span>
              {available ? "Available" : "Not available"}
            </Link>
          </Button>
        </div>
      </FadeIn>
    </div>
  );
}

export default Hero;
