// components/heading.tsx
import { cn } from "@/lib/utils";
import { cva, VariantProps } from "class-variance-authority";
import React from "react";

const headingVariants = cva("tracking-tight text-pretty text-highlighted", {
  variants: {
    size: {
      default: "text-xl sm:text-xl lg:text-2xl font-medium",
      big: "font-bold text-2xl sm:text-3xl lg:text-4xl",
    },
  },
  defaultVariants: {
    size: "default",
  },
});

function Heading({
  className,
  size,
  asChild = false,
  ...props
}: React.ComponentProps<"p"> &
  VariantProps<typeof headingVariants> & {
    asChild?: boolean;
  }) {
  return <p className={cn(headingVariants({ size, className }))} {...props} />;
}

export default Heading;

// app/components/shared/Heading.vue
<template>
  <div
    v-if="title"
    :class="`text-pretty tracking-tight text-highlighted ${uiSize}`"
  >
    {{ title }}
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  title?: string;
  size?: "md" | "lg";
}>();

const sizeClasses = {
  md: "text-xl sm:text-xl lg:text-2xl font-medium",
  lg: "font-bold text-2xl sm:text-3xl lg:text-4xl",
};

const uiSize = sizeClasses[props.size || "md"];

if (!props.title) {
  console.warn("[Heading] component requires `title` prop to render.");
}
</script>
