// components/blog/shared/tag/tag.tsx
import { cva, type VariantProps } from "class-variance-authority";
import React from "react";
import { cn } from "@/lib/utils";
import getTagStyles from "./styles";

export type Props = {
  name: string;
  path?: string;
  variant?: "default" | "outline" | "subtle";
};

// Tag style variants based on tag names
const tagVariants = cva(
  "rounded group transition duration-200 w-max text-sm font-medium px-1.5 py-0.5 text-xs",
  {
    variants: {
      variant: {
        default: "border",
        outline: "border-1 bg-transparent",
        subtle: "border-0",
      },
      clickable: {
        true: "cursor-pointer hover:opacity-80",
        false: "cursor-default",
      },
    },
    defaultVariants: {
      variant: "default",
      clickable: false,
    },
  }
);

function Tag({ name, path, variant = "default" }: Props) {
  const isClickable = path ? true : false;
  const tagStyles = getTagStyles(name, variant, isClickable);

  const TagComponent = isClickable ? "a" : "div";

  return (
    <TagComponent
      href={path}
      className={cn(
        tagVariants({ variant, clickable: isClickable }),
        tagStyles
      )}
    >
      # {name}
    </TagComponent>
  );
}

export default Tag;

// app/components/shared/Tag.vue
<template>
  <component
    :is="isClickable ? 'NuxtLink' : 'div'"
    :to="isClickable ? path : undefined"
    :class="tagClasses"
  >
    # {{ name }}
  </component>
</template>

<script lang="ts" setup>
import { cva } from "~/utils/cva";
import { cn } from "~/utils/cn";
import { getTagStyles, type TagVariant } from "~/utils/tagStyles";

export interface Props {
  name: string;
  path?: string;
  variant?: TagVariant;
}

const props = withDefaults(defineProps<Props>(), {
  variant: "default",
});

const isClickable = computed(() => Boolean(props.path));

// Tag style variants using cva
const tagVariants = cva(
  "rounded group transition duration-200 w-max text-sm font-medium px-1.5 py-0.5 text-xs",
  {
    variants: {
      variant: {
        default: "border",
        outline: "border-1 bg-transparent",
        subtle: "border-0",
      },
      clickable: {
        true: "cursor-pointer hover:opacity-80",
        false: "cursor-default",
      },
    },
    defaultVariants: {
      variant: "default",
      clickable: false,
    },
  }
);

const tagClasses = computed(() => {
  const baseClasses = tagVariants({
    variant: props.variant,
    clickable: isClickable.value,
  });
  const dynamicStyles = getTagStyles(
    props.name,
    props.variant,
    isClickable.value
  );
  return cn(baseClasses, dynamicStyles);
});
</script>
