// app/about/page.tsx
import Heading from "@/components/heading";
import Hero from "@/components/landing/hero";
import { getPageData } from "@/lib/api/pages";
import { getConfig } from "@/lib/app.config";

export default function Page() {
  const page = getPageData("about");
  const {} = getConfig();

  return (
    <div className="mb-8">
      <Heading className="mb-2" size="big">
        {page.title}
      </Heading>
      <p className="text-muted-foreground">{page.description}</p>
    </div>
  );
}

// components/landing/About.vue
<template>
  <Section :title="page.about.title">
    <div class="text-sm sm:text-md lg:text-sm text-muted">
      {{ page.about.description }}
    </div></Section
  >
</template>

<script lang="ts" setup>
defineProps<{
  page: {
    about: {
      title: string;
      description: string;
    };
  };
}>();
</script>

<style></style>
